name: Airline delays scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libxml2-dev \
            libmagick++-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev \
            pandoc \
            git

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/Rlib
          key: ${{ runner.os }}-R-${{ hashFiles('**/scripts/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/Rlib
          echo 'R_LIBS_USER=~/Rlib' >> ~/.Renviron
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ~/.Rprofile
          Rscript -e 'install.packages("tidyverse", dependencies = TRUE, lib="~/Rlib")'
          Rscript -e 'install.packages(c("jsonlite", "remotes", "magick", "usethis"), dependencies = TRUE, lib="~/Rlib")'
          Rscript -e 'remotes::install_github("munichrocker/DatawRappr", lib="~/Rlib", auth_token=Sys.getenv("GITHUB_PAT"))'
          Rscript -e '.libPaths("~/Rlib"); if (!require("tidyverse", lib.loc = "~/Rlib")) stop("tidyverse did not install")'


      - name: Run scraper
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CANCELED_KEY: ${{ secrets.CANCELED_KEY }}
          CANCELEDPER_KEY: ${{ secrets.CANCELED_PER }}
          DELAYED_KEY: ${{ secrets.DELAYED_KEY }}
          DELAYEDPER_KEY: ${{ secrets.DELAYEDPER_KEY }}

        run: |
                . ~/.Renviron
                Rscript "airline_delay_update.R"

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): refresh airline CSVs"
          file_pattern: |
            toupdate/airline_canceled.csv
            toupdate/airline_canceled_per.csv
            toupdate/airline_delayed.csv
            toupdate/airline_delayed_per.csv
